remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "neon"   # try: default, air, contrast, dark, dirt, neon, mint, plum, sunrise

title: "Shana Siddik"
description: "Welcome to my personal page!"

plugins:
  - jekyll-include-cache

# Powers the photo/bio/social sidebar shown on your page
author:
  name: "Shana Siddik"
  avatar: "/assets/images/profile.jpg"
  bio: "Biomedical Informatics MA student @ Columbia University"
  location: "New York, NY"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:shanasiddik@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/shana-siddik-7aa611263"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yourusername"
